[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = ${ADMIN_PASSWORD}
db_host = ${DB_HOST}
db_port = ${DB_PORT}
db_user = ${DB_USER}
db_password = ${DB_PASSWORD}
db_name = ${DB_NAME}
list_db = False
proxy_mode = True
workers = ${WORKERS:-4}
max_cron_threads = ${MAX_CRON_THREADS:-2} 